using System;
using System.Collections.Generic;
using System.Text;

namespace QuranVerses
{
    public static class Constants
    {
        // Languages
        public static string LanguageBosnian = "bih";
        public static string LanguageEnglish = "eng";
        public static string LanguageGerman = "de";

        // Surah names
        public static string Surah1Name = "Al-Fatiha";
        public static string Surah2Name = "Al-Beqarah";
        public static string Surah3Name = "Ali-Imran";
        public static string Surah4Name = "An-Nisa";
        public static string Surah5Name = "Al-Maidah";
        public static string Surah6Name = "Al-An'am";
        public static string Surah7Name = "Al-Ar'af";
        public static string Surah8Name = "Al-Anfal";
        public static string Surah9Name = "At-Tawbah";
        public static string Surah10Name = "Yunus";
        public static string Surah11Name = "Hud";
        public static string Surah12Name = "Yusuf";
        public static string Surah13Name = "Ar-Ra'd";
        public static string Surah14Name = "Ibrahim";
        public static string Surah15Name = "Al-Hijr";
        public static string Surah16Name = "An-Nahl";
        public static string Surah17Name = "Al-Isra";
        public static string Surah18Name = "Al-Kahf";
        public static string Surah19Name = "Maryam";
        public static string Surah20Name = "Taha";
        public static string Surah21Name = "Al-Anbya";
        public static string Surah22Name = "Al-Haj";
        public static string Surah23Name = "Al-Mu'minun";
        public static string Surah24Name = "At-Nur";
        public static string Surah25Name = "Al-furqan";
        public static string Surah26Name = "Ash-Shu'ara";
        public static string Surah27Name = "An-Naml";
        public static string Surah28Name = "Al-Qasas";
        public static string Surah29Name = "Al-'Ankabut";
        public static string Surah30Name = "Ar-Rum";
        public static string Surah31Name = "Luqman";
        public static string Surah32Name = "As-Sajdah";
        public static string Surah33Name = "Al-Ahzab";
        public static string Surah34Name = "Saba";
        public static string Surah35Name = "Fatir";
        public static string Surah36Name = "Ya-Sin";
        public static string Surah37Name = "As-Saffat";
        public static string Surah38Name = "Sad";
        public static string Surah39Name = "Az-Zumar";
        public static string Surah40Name = "Ghafir";
        public static string Surah41Name = "Fussilat";
        public static string Surah42Name = "Ash-Shuraa";
        public static string Surah43Name = "Az-Zukhruf";
        public static string Surah44Name = "Al-Dukhan";
        public static string Surah45Name = "Al-Jathiyah";
        public static string Surah46Name = "Al-Ahqaf";
        public static string Surah47Name = "Muhammad";
        public static string Surah48Name = "Al-Fath";
        public static string Surah49Name = "Al-Hujurat";
        public static string Surah50Name = "Qaf";
        public static string Surah51Name = "Adh-Dhariyat";
        public static string Surah52Name = "At-Tur";
        public static string Surah53Name = "An-Najm";
        public static string Surah54Name = "Al-Qamar";
        public static string Surah55Name = "Ar-Rahman";
        public static string Surah56Name = "Al-Waqi'ah";
        public static string Surah57Name = "Al-Hadid";
        public static string Surah58Name = "Al-Mujadila";
        public static string Surah59Name = "Al-Hashr";
        public static string Surah60Name = "Al-Mumtahanah";
        public static string Surah61Name = "As-Saf";
        public static string Surah62Name = "Al-Jumu'ah";
        public static string Surah63Name = "Al-Munafiqun";
        public static string Surah64Name = "At-Taghabun";
        public static string Surah65Name = "At-Talaq";
        public static string Surah66Name = "At-Tahrim";
        public static string Surah67Name = "Al-Mulk";
        public static string Surah68Name = "Al-Qalam";
        public static string Surah69Name = "Al-Haqqah";
        public static string Surah70Name = "Al-Ma'arij";
        public static string Surah71Name = "Nuh";
        public static string Surah72Name = "Al-Jinn";
        public static string Surah73Name = "Al-Muzzammil";
        public static string Surah74Name = "Al-Muddaththir";
        public static string Surah75Name = "Al-Qiyamah";
        public static string Surah76Name = "Al-Insan";
        public static string Surah77Name = "Al-Mursalat";
        public static string Surah78Name = "An-Naba";
        public static string Surah79Name = "Al-Nazi'at";
        public static string Surah80Name = "Abasa";
        public static string Surah81Name = "At-Takwir";
        public static string Surah82Name = "Al-Infitar";
        public static string Surah83Name = "Al-Mutaffifin";
        public static string Surah84Name = "Al-Inshiqaq";
        public static string Surah85Name = "Al-Buruj";
        public static string Surah86Name = "At-Tariq";
        public static string Surah87Name = "Al-Ala";
        public static string Surah88Name = "Al-Ghashiyah";
        public static string Surah89Name = "Al-Fajr";
        public static string Surah90Name = "Al-Balad";
        public static string Surah91Name = "Ash-Shams";
        public static string Surah92Name = "Al-Layl";
        public static string Surah93Name = "Ad-Duhaa";
        public static string Surah94Name = "Ash-Sharh";
        public static string Surah95Name = "At-Tin";
        public static string Surah96Name = "Al-'Alaq";
        public static string Surah97Name = "Al-Qadr";
        public static string Surah98Name = "Al-Bayyinah";
        public static string Surah99Name = "Az-Zalzalah";
        public static string Surah100Name = "Al-'Adiyat";
        public static string Surah101Name = "Al-Qariah";
        public static string Surah102Name = "At-Takathur";
        public static string Surah103Name = "Al-'Asr";
        public static string Surah104Name = "Al-Humazah";
        public static string Surah105Name = "Al-Fil";
        public static string Surah106Name = "Quraysh";
        public static string Surah107Name = "Al-Ma'un";
        public static string Surah108Name = "Al-Kawthar";
        public static string Surah109Name = "Al-Kafirun";
        public static string Surah110Name = "An-Nasr";
        public static string Surah111Name = "Al-Masad";
        public static string Surah112Name = "Al-Ikhlas";
        public static string Surah113Name = "Al-Falaq";
        public static string Surah114Name = "An-Nas";

    }
}
